import Head from "next/head";
import Image from "next/image";
import Header from "@components/Header";
import Container from "@components/Container/";
import styles from "@styles/Home.module.scss";
import data from "@data/products.json";
import Button from "@components/button/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Electronic | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com"></link>
        <link rel="preconnect" href="https://cdn.snipcart.com"></link>
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css"
        />
      </Head>
      <Header />
      <main>
        <Container>
          <section className={styles.productCard}>
            {data.map((product) => (
              <article key={product.id} className={styles.product}>
                <figure>
                  <Image
                    src={product.image}
                    width="640"
                    height="510"
                    alt="airpods"
                  />
                </figure>
                <h1>{product.name}</h1>
                <p> $ {product.price} </p>
                <Button
                  className="snipcart-add-item"
                  data-item-id={product.id}
                  data-item-price={product.price}
                  data-item-url="/"
                  data-item-description=""
                  data-item-image={product.image}
                  data-item-name={product.name}
                />
              </article>
            ))}
          </section>
        </Container>
      </main>

      <footer className={styles.footer}>
        <p>&copy; Fritz Gerlin sellPoke {new Date().getFullYear()}</p>
      </footer>
      <script
        async
        src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js"
      ></script>
      <div
        hidden
        id="snipcart"
        data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
      ></div>
    </div>
  );
}
